const ApplicationsActionTypes = {
  GET_MOST_RECENT_APPLICATIONS: "GET_MOST_RECENT_APPLICATIONS",
  GET_APPLICATIONS_FOR_APPLICATIONS_PAGE:
    "GET_APPLICATIONS_FOR_APPLICATIONS_PAGE"
};

export default ApplicationsActionTypes;
