const ApplicationsActionTypes = {
  GET_MOST_RECENT_APPLICATIONS: "GET_MOST_RECENT_APPLICATIONS",
  GET_APPLICATIONS_FOR_APPLICATIONS_PAGE:
    "GET_APPLICATIONS_FOR_APPLICATIONS_PAGE",
  GET_STATS_FOR_DASH: "GET_STATS_FOR_DASH"
};

export default ApplicationsActionTypes;
