const SettingsActionTypes = {
  TRIGGER_USER_SETTINGS: "TRIGGER_USER_SETTINGS",
  TRIGGER_MENU_EXPAND_COLLAPSE: "TRIGGER_MENU_EXPAND_COLLAPSE",
  TRIGGER_ADD_OBJECT: "TRIGGER_ADD_OBJECT"
};

export default SettingsActionTypes;
