const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_IS_AUTHENTICATED: "SET_IS_AUTHENTICATED",
  LOGOUT_CURRENT_USER: "LOGOUT_CURRENT_USER",
  REGISTER_USER: "REGISTER_USER"
};

export default UserActionTypes;
